import './globals.css'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">

        <body className={inter.className}>
        <nav className={"flex"}>
            <div className={"flex-1"}>
                <p>LOGO</p>
            </div>
        </nav>
        {children}

        <footer>
            <p>Footer</p>
        </footer>

        </body>

        </html>
    )
}
